# Generated by Django 5.2.7 on 2025-10-10 14:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default=core.models.generate_token, max_length=16, unique=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('expires_at', models.DateTimeField(default=core.models.get_burnout_time)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URLShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default=core.models.generate_token, max_length=16, unique=True)),
                ('original_url', models.URLField()),
                ('expires_at', models.DateTimeField(default=core.models.get_burnout_time)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
