name: 🚀 CI/CD for Django on EC2

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint  # only run if lint passes
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: temshare_proj
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        working-directory: temshare_proj
        run: |
          source ${{ secrets.VENV_DIR }}/bin/activate
          python manage.py test core

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: test  # only run if tests pass
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull origin main
            source ${{ secrets.VENV_DIR }}/bin/activate
            pip install -r tempshare/temshare_proj/requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
